### PR TITLE
Added sendWebhookMessage function

### PR DESCRIPTION
**Pull request by robjschroeder**
Function used to send failure and success notifications to a Microsoft Teams channel via an incoming webhook.

### CODE REVIEW

**Comment by colorenz** [comment]
Maybe we could give the webhook url in $10. Then you could also simply change it.

**Comment by robjschroeder** [comment]
That's an awesome idea @colorenz !!!

**Comment by dan-snelson** [comment]
@robjschroeder or @colorenz:

Will one of you be submitting another PR for this?

**Comment by robjschroeder** [comment]
@dan-snelson done! #31, looks like @colorenz may have beat me by 2 hours lol

**Comment by colorenz** [comment]
Nope my PR added only a button action to the Teams message card.

**Pull request merged**
