### PR TITLE
Version 1.10 theile

### PR DESCRIPTION
**Pull request by Theile**
## Version 1.10.st, 22-May-2023, Søren Theilgaard
- icon URL can be hash, URL or file path to png, jpg, icns, app
- stuff moved around to have most all variables in the top
- markings used
- using JSON files (from /var/tmp/): required.json, recommended.json, complete.json, if present. Removes them after running.
- Lot’s of other changes, too.

### CODE REVIEW

**Comment by theilgaard** [comment]
lgtm :rocket: ;)

**Comment by Theile** [comment]
Did you get tagget here?

**Comment by Theile** [comment]
Yes, I see that, but I did not tag you on purpose. Didn't know that the at-sign would do that.

**Comment by dan-snelson** [comment]
One word, @Theile: **Wowzers!**

**Comment by dan-snelson** [comment]
@Theile: After reviewing, I'm thinking this PR may better fit in a "MSP" fork of SYM; thoughts?

**Comment by dan-snelson** [comment]
@Theile: As discussed via direct-message, I'll go ahead an close this PR; thanks for all your contributions.

**Pull request closed without merging**
