### PR TITLE
Configuration Names and Descriptions as Variables

### PR DESCRIPTION
**Pull request by theadamcraig**
I've added variables for configuration names and descriptions to make one set of variables that need updated to update the configurations throughout the entire script.

This will make the script easier to customize for people who want different names and application sets for their configurations.

### CODE REVIEW

**Comment by drtaru** [comment]
The only issue I see with this is it implies a limitation of three configurations which is not the case, you can have as many as you want / need.

**Comment by dan-snelson** [comment]
Thanks, @theadamcraig!

Fair point, @drtaru, but I do see this as an improvement of the currently hard-coded Configuration labels we're using internally.

**Comment by dan-snelson** [comment]
@theadamcraig: I just changed the base branch from `main`  to `1.11.0` and there are now conflicts.

Please resolve. Thanks.

**Comment by theadamcraig** [comment]
I've updated to resolve  the conflicts.

@drtaru I hope that these changes will help users who want to add a 4th, or more, configurations find out where they need to be updated by being able to easily search and find variable names.

**Pull request merged**
