### PR TITLE
Installomator progress for individual listitems

### PR DESCRIPTION
**Pull request by croaker-1**
The idea is to use the SwiftDialog integration in Installomator to allow Setup-Your-Mac to display download/install progress for individual list items.

Here is an example using Microsoft Teams: 
Setup a Microsoft Teams step in your policyJSON, with `listitem` matching the `name` variable from `Installomator.sh`
```
"listitem": "Microsoft Teams",
"icon": ...
```
Then add the following Installomator parameters to your install policy, making sure `DIALOG_LIST_ITEM_NAME` matches `listitem` from your policyJSON
```
DIALOG_LIST_ITEM_NAME="Microsoft Teams"`
DIALOG_CMD_FILE="/var/tmp/dialogCommandFileSetupYourMac"
```

image

This is my first pull request ever so please patient with me.

### CODE REVIEW

**Comment by croaker-1** [comment]
The idea here is to use the SwiftDialog integration in Installmator to allow Setup-Your-Mac to display download/install progress for individual items.

For example, use the following parameters when installing Microsoft Teams
DIALOG_LIST_ITEM_NAME="Microsoft Teams"
DIALOG_CMD_FILE="/var/tmp/dialogCommandFileSetupYourMac"

image

This is my first pull request ever so please patient with me.

**Comment by dan-snelson** [comment]
Thanks, @croaker-1!

What happens for non-Installomator policies?

**Comment by croaker-1** [comment]
All policies will continue get the status passed by Set-Up-Your-Mac (including Installomator policies). Installomator appends the SwiftDialog command with the listitem progress so nothing should change for non-Installomator policies.

image

**Comment by dan-snelson** [comment]
Greetings, @croaker-1!

Today I learned that if I delete a branch to which I have associated your PR, your PR will be auto-closed; sorry about that.

(I **do** plan to utilize your code in SYM `2`.)

**Pull request closed without merging**
