### PR TITLE
Streamline policyJSON Section

### PR DESCRIPTION
**Pull request by rougegoat**
Split each potential step out into a separate variable that can be added 
Centralized these variables in one section
Simplified how to change what gets deployed in Required, Recommended, and Complete 
Reduced duplicate code, which reduces future modifications people need to make

This also helps streamline adding future steps for programs not currently included.

### CODE REVIEW

**Comment by rougegoat** [comment]
Sorry for all the PRs!  Sometimes I gotta get an idea out before I forget it.

**Comment by dan-snelson** [comment]
Thanks, @rougegoat.

(I'll take a look once `1.10.0` is released.)

**Comment by dan-snelson** [comment]
@rougegoat: Please give me some time to counsel with others on how best to proceed with this PR. Thanks.

**Comment by rougegoat** [comment]
Understandable.  I should note the main goal here was less rewriting it for à la carte style app installs and more reducing duplicate code.  That way, going forward if you have to update the Rosetta or Recon (for example) json snippets, you only have to adjust it in one place instead of four.  It's just that when this is done, it kind of opens the door to that functionality should that route be needed down the line.

**Comment by theadamcraig** [comment]
I like the core concept of this idea a lot.

**Pull request closed without merging**
