### PR TITLE
Added a potentialAction to the Teams Actioncard

### PR DESCRIPTION
**Pull request by colorenz**
Added a potentialAction to the Teams Actioncard and also the Hostname as Computername

image

### CODE REVIEW

**Comment by dan-snelson** [comment]
@colorenz!

Headed to lunch; will review before my afternoon nap.

**Comment by colorenz** [comment]
bon appétit

**Comment by robjschroeder** [comment]
I have been able to do something similar with my card. I have the URL to the device under the 'Mac Enrollment' title. To do this I had to have a configuration profile deployed to the computer that would get the `$JSSID`. Then I read that ID number in my SYM script to put together a full URL. Not sure we can do this without the added configuration profile from Jamf without having to include an API call in SYM.

**Comment by colorenz** [comment]
Nice. Yeah i have also such a profile on my macs🤣.

But i think not many admins use such profiles, so that was the best solution I figured out.

Or is there any other place on the device were we can find the Device ID?

**Comment by dan-snelson** [comment]
Seems like more and more Mac Admins are running an initial `recon` as the first `policyJSON` > `listitem`, which returns `computer_id`.

**Comment by dan-snelson** [comment]
@colorenz: Please pardon my lack o' `git` wizardry; there are now conflicts.

Will you please re-submit after having pulled `1.10.0-rc17` ?

**Comment by iDrewbs** [comment]
@colorenz what is that screenshot from?

**Comment by robjschroeder** [comment]
@dan-snelson should there be a recon inside the function then to grab the id to build the action card's uri? This would help in case an admin doesn't have a recon as first policy but still wanted to use the Teams webhook. If I get some time tonight I can try this out.

**Comment by robjschroeder** [comment]
Is there a way to reference the computer's inventory record url based on it's UUID? In a similar way to how @colorenz referenced the computer's url based on host name?

**Comment by colorenz** [comment]
Please make the PR. I am sleeping😅 it's 5 a.m in Germany.

Or you need to wait.

**Comment by robjschroeder** [comment]
Done @dan-snelson PR #32. Enjoy your sleep @colorenz !!

**Comment by dan-snelson** [comment]
Thanks, @robjschroeder.

@colorenz: Should this PR now be closed? (I **do** want to be certain to recognize your contribution.)

**Pull request closed without merging**
